name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  quick-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt

    - name: Quick lint check
      run: |
        pip install flake8
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run unit tests
      run: |
        pytest tests/ -v --tb=short -x
      env:
        PYTHONPATH: ${{ github.workspace }}/src

    - name: Test Docker build
      run: |
        docker build -t hippo-bot:pr-test .

  approve-or-request-changes:
    runs-on: ubuntu-latest
    needs: [quick-tests]
    if: always()
    
    steps:
    - name: Check test results
      run: |
        if [ "${{ needs.quick-tests.result }}" == "success" ]; then
          echo "✅ PR checks passed! Ready for review."
        else
          echo "❌ PR checks failed. Please fix the issues before review."
          exit 1
        fi